<script setup lang="ts">
import { getCollection, getContent } from '../../content';
import ContentCard from '../ContentCard.vue';
const collection = getCollection('home:field-notes');
const lead = getContent(collection.featuredId);
const stories = collection.itemIds.filter(id => id !== collection.featuredId).map(getContent);
</script>
<template><section id="field-notes" class="home-stage home-field-notes" aria-labelledby="field-notes-title"><div class="home-inner"><div class="home-heading" data-home-reveal><div><p class="eyebrow">03 / FIELD NOTES</p><h2 id="field-notes-title">Worth an <em>afternoon.</em></h2></div><RouterLink to="/journal" class="text-link">All field notes <span aria-hidden="true">↗</span></RouterLink></div><div class="feature-selection"><ContentCard class="lead-story" :content="lead" image-sizes="(max-width:800px) 90vw, 48vw" data-home-reveal="art" /><div class="supporting-stories" data-home-reveal><ContentCard v-for="story in stories" :key="story.id" :content="story" image-sizes="(max-width:550px) 90px, 150px" /></div></div></div></section></template>
<style scoped>
.home-field-notes{background:#fbfaf6}.feature-selection{display:grid;grid-template-columns:1.15fr 1fr;gap:6%;align-items:start}.lead-story :deep(.content-card-copy h3){font-size:clamp(30px,3vw,40px)}.lead-story :deep(.content-card-summary){display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.lead-story :deep(.content-card-bottom){padding-top:16px}.supporting-stories :deep(.content-card){display:grid;grid-template-columns:minmax(95px,30%) 1fr;gap:22px;padding:18px 0;border-top:1px solid var(--rule)}.supporting-stories :deep(.content-card:first-child){padding-top:0;border-top:0}.supporting-stories :deep(.content-card-art){aspect-ratio:1;border-radius:3px}.supporting-stories :deep(.content-card-copy){padding:0}.supporting-stories :deep(.content-card-meta){font-size:11px;flex-direction:row;gap:4px;margin-bottom:9px}.supporting-stories :deep(.content-card-copy h3){font-size:24px}.supporting-stories :deep(.content-card-summary){font-size:14px;margin-top:10px;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.supporting-stories :deep(.content-card-bottom){font-size:12px;padding-top:12px}
@media(max-width:800px){.feature-selection{grid-template-columns:1fr;gap:32px}.supporting-stories :deep(.content-card){grid-template-columns:150px 1fr}.supporting-stories :deep(.content-card:first-child){padding-top:25px;border-top:1px solid var(--rule)}.supporting-stories :deep(.content-card-meta){flex-direction:row}}
@media(max-width:550px){.supporting-stories :deep(.content-card){grid-template-columns:90px 1fr;gap:17px}.supporting-stories :deep(.content-card-copy h3){font-size:23px}.supporting-stories :deep(.content-card-summary){display:none}.supporting-stories :deep(.content-card-meta){flex-direction:column}.lead-story :deep(.content-card-copy h3){font-size:32px}}
</style>
