<script setup lang="ts">
import { worlds } from '../../content';
</script>
<template><section id="worlds" class="home-stage home-worlds" aria-labelledby="worlds-title"><div class="home-inner"><div class="home-heading" data-home-reveal><div><p class="eyebrow">01 / PICK YOUR FIRST STOP</p><h2 id="worlds-title">A place for your <em>curiosity.</em></h2></div><p>Take the scenic route.<br />Or follow something small.</p></div><div class="world-portals" data-home-reveal="art"><RouterLink v-for="world in worlds" :key="world.id" :to="`/${world.id}`" :class="['world-portal',`portal-${world.id}`]"><div class="portal-art"><img :src="`/art/scenes/${world.id}.webp`" alt="" width="1536" height="1024" loading="lazy" /></div><span class="portal-number">{{ world.symbol }} / OHIO</span><div class="portal-copy"><h3>{{ world.title }}<span aria-hidden="true">↗</span></h3><p>{{ world.invitation }}</p></div></RouterLink></div></div></section></template>
<style scoped>
.home-worlds{background:var(--surface)}
.world-portals{display:grid;grid-template-columns:1fr 1fr;gap:22px}.world-portal{position:relative;isolation:isolate;overflow:hidden;display:flex;flex-direction:column;justify-content:space-between;min-height:clamp(220px,26svh,290px);padding:27px 30px;color:white;background:var(--ink);border-radius:3px}.portal-art{position:absolute;inset:0;z-index:-1}.portal-art::after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,#12233440,#12233410 20%,#122334e6)}.portal-art img{width:100%;height:100%;object-fit:cover;transition:transform 350ms var(--ease)}.portal-number{align-self:start;background:#14243cc4;padding:7px 9px;font-size:11px;letter-spacing:.12em}.portal-copy h3{display:flex;align-items:center;justify-content:space-between;font-size:42px;line-height:1.15;color:white}.portal-copy h3 span{font:30px var(--font-body);transition:transform 220ms var(--ease)}.portal-copy p{font-size:15px;line-height:1.6;margin-top:10px;max-width:36ch;color:#fff}.portal-culture{border-top-right-radius:38px}.portal-culture h3{font-family:var(--font-editorial);font-style:italic}.portal-live{border-bottom-right-radius:38px}
@media(hover:hover) and (prefers-reduced-motion:no-preference){.world-portal:hover img{transform:scale(1.035)}.world-portal:hover h3 span{transform:translate(3px,-3px)}}
:global(html[data-input=keyboard]) .portal-art img,:global(html[data-input=keyboard]) .portal-copy h3 span{transform:none;transition:none}
@media(max-width:700px){.world-portals{grid-template-columns:1fr}.world-portal{min-height:235px;padding:25px}.portal-copy h3{font-size:40px}}
</style>
