<template>
  <section id="welcome" class="home-stage home-welcome" aria-labelledby="welcome-title"><div class="home-inner">
    <div class="welcome-grid"><div class="welcome-copy">
      <p class="eyebrow" data-home-reveal>✳ OHIO-CHAN HERE!</p>
      <h1 id="welcome-title" data-home-reveal>Oh, hello<br /><em>Ohio.</em><span aria-hidden="true">♡</span></h1>
      <div data-home-reveal><p class="welcome-identity">Civic idol, local girl,<br /><em>your Ohio guide.</em></p><p class="welcome-dek">Oh, hi! I’m Ohio-chan. Market mornings, workshop visits, quiet library afternoons… I have a few favorites to show you. Come along. ♡</p><a href="#worlds" class="button">Where to first? <span aria-hidden="true">↘</span></a></div>
    </div><figure class="welcome-portrait" data-home-reveal="art"><span class="welcome-watermark" aria-hidden="true">OH</span><img src="/ohio-chan-vtuber.webp" srcset="/art/characters/welcome-480.webp 480w, /art/characters/welcome-768.webp 768w, /ohio-chan-vtuber.webp 1024w" sizes="(max-width:700px) 85vw, 48vw" width="1024" height="1536" fetchpriority="high" alt="Ohio-chan welcomes you with a microphone and an outstretched hand" /><figcaption>YOUR GUIDE<strong>Ohio-chan ♡</strong></figcaption></figure></div>
    <div class="welcome-bottom"><span>A LITTLE CLOSER TO THE BUCKEYE STATE</span><a href="#worlds">01 / Four ways in <span aria-hidden="true">↓</span></a></div>
  </div></section>
</template>
<style scoped>
.home-welcome{background:#e8eff2;isolation:isolate;overflow:hidden}.home-welcome::before{content:'';position:absolute;inset:0;z-index:-1;background:linear-gradient(90deg,#e8eff2 12%,#e8eff2ed 35%,#e8eff250 100%),url('/travel-anime.webp') center/cover}.welcome-grid{display:grid;grid-template-columns:1fr 1fr;gap:2%;align-items:center}.welcome-copy{position:relative;z-index:2;padding:18px 0 30px}.welcome-copy h1{font-size:clamp(72px,8.2vw,118px);line-height:.98;letter-spacing:-.07em;margin:26px 0 28px}.welcome-copy h1 em,.welcome-identity em{color:var(--accent)}.welcome-copy h1>span{font-size:.4em;margin-left:18px}.welcome-identity{font:500 clamp(22px,2vw,27px)/1.35 var(--font-heading);letter-spacing:-.035em}.welcome-dek{font-size:17px;line-height:1.75;max-width:34ch;margin:20px 0 26px;color:var(--ink-soft)}.welcome-portrait{position:relative;display:flex;align-items:center;justify-content:center;isolation:isolate;min-width:0}.welcome-portrait img{width:112%;max-width:none;height:clamp(500px,72svh,740px);object-fit:contain}.welcome-watermark{position:absolute;z-index:-1;font:700 clamp(190px,26vw,370px)/1 var(--font-heading);letter-spacing:-.09em;color:#ffffffa8}.welcome-portrait figcaption{position:absolute;bottom:9%;right:-1%;background:#faf8f0e6;border-left:2px solid var(--accent);padding:12px 18px;font-size:10px;letter-spacing:.12em}.welcome-portrait strong{display:block;font:500 23px var(--font-heading);letter-spacing:-.04em;margin-top:6px}.welcome-bottom{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-top:12px;padding-top:14px;border-top:1px solid #18243c26;font-size:11px;letter-spacing:.04em}.welcome-bottom a{display:flex;align-items:center;gap:24px;min-height:44px}
@media(min-width:1024px) and (min-height:720px){.home-welcome{padding-block:24px}}
@media(min-width:701px) and (max-width:1000px){.welcome-copy h1{font-size:78px}.welcome-dek{font-size:16px}.welcome-portrait img{height:580px;width:125%}}
@media(max-width:700px){.home-welcome::before{background:linear-gradient(180deg,#e8eff2f5 0%,#e8eff2ee 56%,#e8eff260 100%),url('/travel-anime.webp') center/cover}.home-welcome{padding-top:30px;padding-bottom:20px}.welcome-grid{grid-template-columns:1fr}.welcome-copy{padding:0}.welcome-copy h1{font-size:clamp(64px,15vw,86px);margin:20px 0 22px}.welcome-dek{font-size:16px;max-width:35ch;margin:16px 0 22px}.welcome-portrait{margin-top:12px}.welcome-portrait img{height:350px;width:100%}.welcome-watermark{font-size:210px}.welcome-portrait figcaption{right:0;bottom:12%}.welcome-bottom{font-size:10px}.welcome-bottom>span{max-width:150px;line-height:1.6}}
</style>
