<script setup lang="ts">
import { getCollection, getContent, getMedia } from '../../content';
const collection = getCollection('home:theme');
const lead = getContent(collection.featuredId);
const art = lead.kind === 'feature' ? getMedia(lead.coverMediaId) : undefined;
const companions = collection.itemIds.filter(id => id !== collection.featuredId).map(getContent);
</script>
<template><section id="in-focus" class="home-stage home-theme" aria-labelledby="theme-title"><div class="home-inner"><p class="eyebrow" data-home-reveal>02 / IN FOCUS · {{ collection.title }}</p><div class="theme-feature"><div class="theme-copy" data-home-reveal><h2 id="theme-title">Small things.<br /><em>Whole worlds.</em></h2><p>{{ collection.dek }}</p><RouterLink :to="lead.canonicalPath" class="text-link">{{ lead.title }} <span aria-hidden="true">↗</span></RouterLink></div><figure class="theme-art" data-home-reveal="art"><RouterLink :to="lead.canonicalPath" :aria-label="lead.title"><img v-if="art" :src="art.src" :srcset="art.variants?.map(item => `${item.src} ${item.width}w`).join(', ')" sizes="(max-width:800px) 90vw, 60vw" :alt="lead.kind === 'feature' ? lead.coverAlt : ''" width="1536" height="1024" loading="lazy" /></RouterLink><figcaption>ILLUSTRATION <span>LOOK A LITTLE CLOSER ↗</span></figcaption></figure></div><div class="theme-companions" data-home-reveal><RouterLink v-for="(item,index) in companions" :key="item.id" :to="item.canonicalPath"><span class="companion-number">0{{ index+1 }}</span><div><p class="eyebrow">A CLOSER LOOK</p><h3>{{ item.title }}</h3><p>{{ item.summary }}</p></div><span aria-hidden="true">↗</span></RouterLink></div><RouterLink to="/topics" class="theme-all text-link">Explore all collections <span aria-hidden="true">↗</span></RouterLink></div></section></template>
<style scoped>
.home-theme{background:#e3ebe7}.theme-feature{display:grid;grid-template-columns:1fr 1.8fr;gap:6%;align-items:center;margin-top:28px}.theme-copy h2{font-size:clamp(43px,4.6vw,66px);line-height:1.04;margin-bottom:24px}.theme-copy h2 em{color:#31675e}.theme-copy>p{font-size:17px;line-height:1.75;color:#3f5956}.theme-copy .text-link{font-size:15px;line-height:1.6;margin-top:24px}.theme-art{min-width:0}.theme-art img{width:100%;height:auto;aspect-ratio:3/2;object-fit:cover;border-radius:3px 56px 3px 3px}.theme-art figcaption{display:flex;justify-content:space-between;gap:16px;font-size:10px;letter-spacing:.08em;margin-top:12px;color:#3f5956}.theme-companions{display:grid;grid-template-columns:1fr 1fr;gap:40px;margin-top:32px;padding-top:24px;border-top:1px solid #b9cbc1}.theme-companions>a{display:flex;gap:18px;align-items:start}.companion-number{font:italic 27px var(--font-editorial);color:#597467}.theme-companions h3{font-size:23px;line-height:1.2;margin:8px 0}.theme-companions p:not(.eyebrow){font-size:14px;line-height:1.65;color:#3f5956}.theme-companions>a>span:last-child{margin-left:auto;font-size:23px}.theme-all{margin-top:20px;font-size:14px}.theme-companions a:hover h3{color:var(--accent)}
@media(max-width:800px){.theme-feature{grid-template-columns:1fr;gap:30px}.theme-copy h2{font-size:48px}.theme-copy>p{max-width:54ch}}
@media(max-width:550px){.theme-companions{grid-template-columns:1fr;gap:24px}.theme-companions>a+a{padding-top:24px;border-top:1px solid #b9cbc1}.theme-copy h2{font-size:45px}}
</style>
